### ISSUE TITLE
Use github4 instead of request for public isssues

### ISSUE THREAD

**Issue by pippinlee** [pippinlee/get-issues#16]
Instead of making http request via `request` module, we should make use the github4 module for all requests to github.

Currently the `getIssues` function uses the `request` module -- since we're switching over github4 module for all other requests, we should do the same for non-auth required requests to github.

**Comment by mikemimik** [comment]
commit: 370a1e0 on my fork will solve this soon.

Will keep up-to-date with progress, and then will merge my fork into a branch in this repo.

**Comment by pippinlee** [comment]
This is done 💯
