### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by seiyria** [pippinlee/get-issues#5]
for this particular project: https://github.com/seiyria/Roguathia

this isn't doing anything besides adding an empty issues folder and an entry in my gitignore. how does this work? is there a way to specify a repository?

**Comment by pippinlee** [comment]
Thanks for noting this @seiyria -- it does sound like a bug!

I was able to clone your repo and run `get-issues` fine within the root of the project, and it collected all open issues and comments.

Let's try understand what's happening: is it creating the files in `issues/` are your end?

Looks like this when I run: ![](https://cldup.com/W1wBTNbgO3.png)

If you're not getting any errors that also problematic and means we should look at adding better error handling.

**Comment by seiyria** [comment]
Strange. I'm on OSX also. I am not seeing _any_ files created, I am only seeing the folder. No errors at all.

**Comment by pippinlee** [comment]
Good info. Just trying to think through other variables. I ran with node v4.2.1. You?

**Comment by seiyria** [comment]
3.2.0 here.

**Comment by pippinlee** [comment]
Cool -- going to setup nvm quickly so that I poke around.

**Comment by pippinlee** [comment]
Another data point: running on v3.2.0 worked fine, which means it's likely not a node version issue, yay!

Two more pieces of info that may help:

* What does running `git remote -v`in `Roguathia/` output?
* Does `get-issues` work in other repos?

**Comment by seiyria** [comment]
I think I know why - it's because the links are ssh, not https.

**Comment by pippinlee** [comment]
Ah, interesting. I have a branch ready that starts using url.format to make URLs a bit less error prone -- but it's setup for https.

I'm not sure of frequency of folks use ssh link vs https for git, but likely worthwhile for us to allow for ssh.

**Comment by seiyria** [comment]
For what it's worth, I never use https if I can use ssh - I hate inputting my credentials all the time.

**Comment by pippinlee** [comment]
@seiyria just landed a patch that should now allow for SSH remote urls––thanks for the help! Let me know if you continue to see this or any other problems. 

I think I setup git like this so that I don't have to auth every time with github https://help.github.com/articles/caching-your-github-password-in-git/

**Comment by seiyria** [comment]
Awesome! Thanks.

Yeah, that's another way to do it. I prefer ssh auth over https auth where possible still, credential caching has caused me problems in the past.
